### ISSUE TITLE
UnboundLocalError: local variable 'toml' referenced before assignment

### ISSUE THREAD

**Issue by leopku** [nZac/flask-tomlconfig#2]
app.py

``` py
import flask
from flask_environment import Config

class MyApp(flask.Flask):
    """docstring for MyApp"""
    # def __init__(self, arg):
    #     super(MyApp, self).__init__()
    #     self.arg = arg

    # config_class = Config   
    def make_config(self, instance_relative=False):
        root_path = self.root_path

        if instance_relative:
            root_path = self.instance_path
        return Config(root_path, self.default_config)

app = MyApp(__name__)
app.config.from_toml('config.toml')

@app.route('/')
def hello():
    return 'hello Flask!'

@app.route('/environment')
def environment():
    return config['DEBUG']

if __name__ == '__main__':
    app.run()
```

Error message

``` py
Traceback (most recent call last):
  File "app.py", line 26, in <module>
    app.config.from_toml('config.toml')
  File "/Users/leo/.pyenv/versions/flask-oauth-server/lib/python2.7/site-packages/flask_environment/__init__.py", line 55, in from_toml
    obj = toml.load(toml_file)
UnboundLocalError: local variable 'toml' referenced before assignment
```

**Comment by leopku** [comment]
fixed by uninstall `toml` and replaced with `pytoml`
